# Generated by Django 3.0.2 on 2020-01-24 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items_inv',
            fields=[
                ('itemsID_inv', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('itemsDesc_inv', models.CharField(max_length=200)),
                ('itemsQnt_inv', models.IntegerField()),
                ('itemsCostPrice_inv', models.IntegerField()),
                ('itemsSellPrice_inv', models.IntegerField()),
                ('itemsTotalPrice_inv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transactions_inv',
            fields=[
                ('OrderID_inv', models.AutoField(primary_key=True, serialize=False)),
                ('Discount_inv', models.FloatField()),
                ('Amount_inv', models.FloatField()),
                ('Date_inv', models.DateTimeField(default=django.utils.timezone.now)),
                ('ImtQnt_inv', models.IntegerField()),
                ('ItmID_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorage.items_inv')),
            ],
            options={
                'unique_together': {('OrderID_inv', 'ItmID_inv')},
            },
        ),
    ]
