# Generated by Django 3.0.2 on 2020-02-10 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_inv',
            name='itemsCostPrice_inv',
            field=models.IntegerField(verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='items_inv',
            name='itemsDesc_inv',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='items_inv',
            name='itemsID_inv',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='items_inv',
            name='itemsQnt_inv',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='items_inv',
            name='itemsSellPrice_inv',
            field=models.IntegerField(verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='items_inv',
            name='itemsTotalPrice_inv',
            field=models.IntegerField(verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='Amount_inv',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='Date_inv',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='Discount_inv',
            field=models.FloatField(verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='ImtQnt_inv',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='ItmID_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventorage.items_inv', verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='transactions_inv',
            name='OrderID_inv',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
